### ISSUE TITLE
config.json can be downloaded from the web and expose db credentials

### ISSUE THREAD

**Issue by mauntrelio** [paskino/carbonara#3]
config.json file should be put in another folder (not reachable from the web but available to PHP and python script for reading) or protected somehow, otherwise it could be downloaded from the web and expose db credentials and other sensitive configuration parameters.

**Comment by paskino** [comment]
maybe worth using htaccess for that?

**Comment by mauntrelio** [comment]
I think your approach was better, I would use again a .config file (in JSON format to enable easy sharing between different programming languages) + using .htaccess file to prevent access to any . file
